// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    Notice: typeof import('./src/components/toast/notice.vue')['default']
    NoticeList: typeof import('./src/components/toast/noticeList.vue')['default']
    StarTwoTone: typeof import('@ant-design/icons-vue')['StarTwoTone']
    Tree: typeof import('./src/components/tree/index.vue')['default']
    TreeNode: typeof import('./src/components/tree/treeNode.vue')['default']
  }
}
